version: '3'
services:
  api:
    build:
      dockerfile: ./docker/dev/Dockerfile
      context: ../hacka-api/.
    command: "yarn dev"
    depends_on:
     - rabbitmq
    ports:
      - "3000:3000"
    links:
      - rabbitmq
    volumes:
      - ../hacka-api/.:/src
  worker:
    build:
      dockerfile: ./docker/dev/Dockerfile
      context: ../hacka-worker/.
    command: "yarn dev"
    depends_on:
     - rabbitmq
    links:
      - rabbitmq
    volumes:
      - ../hacka-worker/.:/src