version: '3'

# volumes:
#   hacka-elastic:
#     driver: local

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_VHOST: moltres
    ports:
      - "15672:15672"
      - "5672:5672"

  # elastic:
  #   image: elasticsearch:6.8.3
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   volumes:
  #     - ./esdata:/usr/share/elasticsearch/data